version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: yarn dev
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - server_node_modules:/app/node_modules
    command: yarn dev
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  node_modules:
  server_node_modules:
  db_data:
